elastic:
  index: news
es:
  hostname: localhost
  port: 9200
  username: admin
  password: password
  
  # SWAGGER
springdoc.swagger-ui.path: /swagger-ui.html
springdoc.api-docs.path: /v1/api-docs

http.cors.allow-methods : OPTIONS, HEAD, GET, POST, PUT, DELETE
http.cors.allow-headers : Authorization, X-Requested-With,X-Auth-Token,Content-Type, Content-Length